FROM ros:tesis_base

ADD arduino_reader.py /home/.
ADD run.sh /home/.
#CMD ["/bin/bash", "-c", "roscore & roslaunch rosbridge_server rosbridge_websocket.launch & sleep 10 && python /home/arduino_reader.py"] 
#CMD roslaunch rosbridge_server rosbridge_websocket.launch 
#CMD python /home/arduino_reader.py

